# Dependencies
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 https://l3126596029.github.io/SKY.github.io/

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             # https://l3126596029.github.io/SKY.github.io/

title:               SKY-盖世英雄

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  盟主QQ:3126596029,有会这方面的可以加QQ帮我。

# The tags listed as entries in the sidebar
sidebar_tags:        [wiki, essay]

# Fallback image and color if not overwritten for tag or post
image:               /public/img/001.jpg
color:               '#A85641'

# Fonts
font:                'Ubuntu Mono, consolas, 微软雅黑'
font_accent:         'Ubuntu Mono, consolas, 微软雅黑'
load_google_fonts:   'consolas'

# About yourself
author:
  name:              'SKY-盖世英雄'

  # This photo will be used in the about section


  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
    关于萌生建立博客的想法，最早来自于太不喜欢贴吧或者mcbbs的排版，而且平时空闲时间也喜欢写一些乱七八糟的东西。

    本来是打算用烂大街的wordpress的，然而它提供的免费版本不能改插件，想要更高的自定义功能需要自己去弄主机并且映射域名。如果算域名主机的花费，一个月恐怕就得花60大洋。然而我只是个穷学生啊。

    之后JJN告诉我可以用jekyll结合github建立免费的静态博客的，套用[模板](https://guides.github.com/features/mastering-markdown/)以后就是你们现在看到的这个界面了

    说实话一直对网页搭建很感兴趣，之前曾经看过黄油的博客，觉得在这种快节奏的网络生活中留下一份自己的宁静也是极好的，很受感动。

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    # facebook:        _username_
    twitter:         SKY
    # google:          _number_
    # vk:              _username_
    # youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    twitch:          SKY
    # steam:           _number_
    reddit:          SKY
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    github:            SKY
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        _firstname_-_lastname_-_string_
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
# google_analytics_id: 'UA-84025722-2'

# Setting a disqus subdomain will enable the comment section
# disqus:            SKY

markdown: kramdown


compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
